"""empty message

Revision ID: 1eed9649a2ca
Revises: 
Create Date: 2020-03-15 18:55:58.708044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eed9649a2ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Family_Doe',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('lucky_number', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Family_Doe')
    # ### end Alembic commands ###
